import config, os

print 'Updating /etc/hosts'
s = '''# Generated by config_server.py
127.0.0.1       localhost
127.0.1.1       tambora
'''

for node in config.node_names:
    s += '%s\t%s\n' % (config.node_info[node], node)

s +='''
# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
'''

fid = open('/etc/hosts', 'w')
fid.write(s)
fid.close()

# Create /etc/mpihosts

s = ""
for node in config.node_names[::-1]:  # Reverse order to get head node last in list
    s += '%s %s\n' % (node, 'slots=4')

fid = open('/etc/mpihosts', 'w')
fid.write(s)
fid.close()

print "/etc/mpihosts created...\n"

# Mounting NAS on the Head Node

try:
    os.mkdir('/mnt/nfs/')
    os.mkdir('/mnt/nfs/modelling_area') #creating mount point
    os.system('chmod ugo+rwx /mnt/nfs/modeling_area/') #modify the permission to permit all
    print "NAS Mount point created"
except:
    pass
    print "NAS Mount point /mnt/nfs/modelling_area is exist!!"

# Modify /etc/fstab file

s = '''# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc           proc    nodev,noexec,nosuid 0       0
# / was on /dev/sda1 during installation
UUID=70f69418-541e-4253-89b7-f3d9b4f804e9 /               ext4    errors=remount-ro 0       1
# swap was on /dev/sda5 during installation
UUID=49c62824-c952-47bf-9d24-d3bc8f12b81e none            swap    sw              0       0
#NAS1 Mount Point
10.1.1.50:/volume1/modeling /mnt/nfs/modeling_area nfs defaults 1 1
'''

fid = open('/etc/fstab', 'w')
fid.write(s)
fid.close()

os.system('mount -a -v')
